apiVersion: v2
name: mongodb-vm
description: MongoDB Enterprise Advanced 8.3.2 on RHEL 9 s390x deployed as an OCP Virt VirtualMachine
type: application
version: 1.0.0
appVersion: "8.3.2"
maintainers:
  - name: IBM SovereignCore
keywords:
  - mongodb
  - enterprise
  - s390x
  - ocpvirt
  - virtualmachine
